### ISSUE TITLE
asyncHelper file wrong path on Windows

### ISSUE THREAD

**Issue by nicolasparada** [leebyron/rollup-plugin-async#1]
input.js

``` js
async function foo() {
  return 'bar'
}

foo().then(console.log)
```

output.js

``` js
import { __async } from 'C:UsersNicolasAppDataLocalTempasyncHelper.1473573104863.js';

function foo() {return __async(function*(){
  return 'bar'
}())}

foo().then(console.log)
```

As you can see, asyncHelper has the wrong path from the temp directory so it cannot be resolved.

OS: Windows 10 x64
Node: v6.5.0
Npm: 3.10.8
package.json:

``` json
{
  "scripts": {
    "start": "rollup -c"
  },
  "devDependencies": {
    "rollup": "0.35.7",
    "rollup-plugin-async": "1.1.0"
  }
}
```

rollup.config.js:

``` js
import async from 'rollup-plugin-async'

export default {
  entry: 'input.js',
  dest: 'output.js',
  plugins: [
    async()
  ]
}
```

**Comment by leebyron** [comment]
Thanks for the report! Sounds like this bug is specific to Windows users. I'll take a look

**Comment by nicolasparada** [comment]
The problem is the `getAsyncHelperFile()` function.
It returns the path with backslashes.

Add a `.replace(/\\/g, '/')` and the problem is solved... I think...

**Comment by senseijames** [comment]
@NicolasParada the `.replace` does not solve the problem for me, sadly.  Rather than letting the code build and throwing a module resolution error when it's run, adding the `.replace` will throw an error on build:

> Error transforming C:\Users\JAMESO~1\AppData\Local\Temp\asyncHelper.1476815879241.js with 'babel' plugin: Unknown plugin "transform-object-rest-spread" specified in "base" at 0, attempted to resolve relative to "C:\Users\JAMESO~1\AppData\Local\Temp"

**Comment by nicolasparada** [comment]
Doesn't work on line 21?

``` js
result.prepend('import { __async, __asyncGen } from "' + getAsyncHelperFile().replace(/\\/g, '/') + '"\n');
```

**Comment by senseijames** [comment]
I'm afraid not; yields:

> Error transforming C:\Users\JAMESO~1\AppData\Local\Temp\asyncHelper.1476818314901.js with 'babel' plugin: Unknown plugin "transform-object-rest-spread" specified in "base" at 0, attempted to resolve relative to "C:\Users\JAMESO~1\AppData\Local\Temp"

**Comment by senseijames** [comment]
Perhaps something else is awry, but I'm still seeing the issue with latest code:

> Error transforming C:\Users\JAMESO~1\AppData\Local\Temp\asyncHelper.1476820024320.js with 'babel' plugin: Unknown plugin "transform-object-rest-spread" specified in "base" at 0, attempted to resolve relative to "C:\Users\JAMESO~1\AppData\Local\Temp"
> ReferenceError: Error transforming C:\Users\JAMESO~1\AppData\Local\Temp\asyncHelper.1476820024320.js with 'babel' plugin: Unknown plugin "transform-object-rest-spread" specified in "base" at 0, attempted to resolve relative to "C:\Users\JAMESO~1\AppData\Local\Temp"

Perhaps there is some pre-processing that is necessary?  Possible to see your rollup.config.js ?

**Comment by Shyam-Chen** [comment]
Not Working...

```js
async function foo(x) {  // 10
  let bar = await Promise
    .resolve(x)
    .then(x => x + 2)  // 10 + 2 = 12
    .then(x => x - 3)  // 12 - 3 = 9
    .then(x => x * 4)  // 9 * 4 = 36
    .then(x => x / 5);  // 36 / 5 = 7.2
  return bar;
}

foo(10)
  .then(
    x => console.log(x),
    err => console.log(err)
  );
// 7.2
```

```js
async function foo(x) {  
  return new Promise((resolve, reject) => {
    setTimeout(() => resolve(console.log(2)), x);
  });
}

async function bar() {
  console.log(1);
  await foo(1000);
  setTimeout(() => console.log(3), 1000);
}

bar();
// 1
// 2 (print after 1 second)
// 3 (print after 2 seconds)
```

**Comment by leebyron** [comment]
Hey all - I just published v1.2.0 - it would be great if someone who uses windows could test to ensure this problem has been solved.

**Comment by nicolasparada** [comment]
Yep, it's working for me now.

**Comment by leebyron** [comment]
Great
